"""Update book and user models

Revision ID: e1093a16aa0a
Revises: cca9b5948120
Create Date: 2024-09-23 23:00:10.000868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1093a16aa0a'
down_revision: Union[str, None] = 'cca9b5948120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('borrow_date', sa.Date(), nullable=True))
    op.add_column('books', sa.Column('return_date', sa.Date(), nullable=True))
    op.add_column('books', sa.Column('borrower_id', sa.Integer(), nullable=True))
    op.drop_index('ix_books_borrow_duration', table_name='books')
    op.drop_constraint('books_user_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['borrower_id'], ['id'])
    op.drop_column('books', 'borrow_duration')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('borrow_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_user_id_fkey', 'books', 'users', ['user_id'], ['id'])
    op.create_index('ix_books_borrow_duration', 'books', ['borrow_duration'], unique=False)
    op.drop_column('books', 'borrower_id')
    op.drop_column('books', 'return_date')
    op.drop_column('books', 'borrow_date')
    # ### end Alembic commands ###
